<a href="https://colab.research.google.com/github/doogiesdj/linearalgebra/blob/main/3_7_5_%EB%B2%A1%ED%84%B0%EA%B3%B5%EA%B0%84%EC%9D%98_%EB%B6%80%EB%B6%84%EA%B3%B5%EA%B0%84_%EA%B5%AC%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from scipy.linalg import null_space

def find_subspace(vectors):
    """
    주어진 벡터 집합으로 생성되는 부분 공간을 구하는 함수
    :param vectors: 벡터들의 리스트 (2차원 리스트 또는 2차원 numpy 배열)
    :return: 부분 공간을 생성하는 벡터들 (2차원 numpy 배열)
    """
    # 주어진 벡터들로 이루어진 행렬
    A = np.array(vectors)

    # 행렬의 랭크를 구함
    rank = np.linalg.matrix_rank(A)

    # 부분 공간의 기저를 구함 (기저 벡터들은 A의 null space의 기저와 동일)
    subspace_basis = null_space(A)

    return subspace_basis.T

# 실습 문제: 다음 벡터 집합의 부분 공간을 구하시오.
vector_sets = [
    [[1, 0, 0], [0, 1, 0]],               # R^3에서 평면을 생성하는 두 벡터
    [[1, 1, 1], [1, 0, 1], [0, 1, 1]],     # R^3의 기저 벡터들
    [[2, 4, 6], [1, 2, 3]],                # 선형 종속 벡터들
    [[1, 2], [3, 4]],                      # R^2의 기저 벡터들
    [[1, 2, 3], [4, 5, 6]],                # R^3의 부분 공간을 생성하는 두 벡터
]

# 각 벡터 집합으로 생성되는 부분 공간을 계산하고 출력
for i, vectors in enumerate(vector_sets):
    subspace = find_subspace(vectors)
    print(f"Vector Set {i+1}: {vectors}")
    print(f"Subspace basis:\n{subspace}\n")

Vector Set 1: [[1, 0, 0], [0, 1, 0]]
Subspace basis:
[[0. 0. 1.]]

Vector Set 2: [[1, 1, 1], [1, 0, 1], [0, 1, 1]]
Subspace basis:
[]

Vector Set 3: [[2, 4, 6], [1, 2, 3]]
Subspace basis:
[[ 0.94491118 -0.30854944 -0.10927077]
 [-0.18898224 -0.78681825  0.58753958]]

Vector Set 4: [[1, 2], [3, 4]]
Subspace basis:
[]

Vector Set 5: [[1, 2, 3], [4, 5, 6]]
Subspace basis:
[[ 0.40824829 -0.81649658  0.40824829]]

