<a href="https://colab.research.google.com/github/doogiesdj/linearalgebra/blob/main/4_4_1_%ED%96%89%EB%A0%AC%EC%9D%98_%EC%83%9D%EC%84%B1_%EB%B0%8F_%EA%B8%B0%EB%B3%B8_%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# 행렬 A와 B 생성
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("행렬 A:")
print(A)
print("\n행렬 B:")
print(B)

# 행렬 덧셈
C = A + B
print("\nA + B:")
print(C)

# 행렬 스칼라 곱
scalar = 3
D = scalar * A
print(f"\n{scalar} * A:")
print(D)


행렬 A:
[[1 2]
 [3 4]]

행렬 B:
[[5 6]
 [7 8]]

A + B:
[[ 6  8]
 [10 12]]

3 * A:
[[ 3  6]
 [ 9 12]]
